# Generated by Django 3.2.14 on 2022-07-19 09:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_rename_entry_entrasdy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrasdy',
            new_name='Entry',
        ),
    ]
