# Generated by Django 3.2.14 on 2022-07-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_entrasdy_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(default='Incomplete', max_length=200),
        ),
    ]
