# Generated by Django 3.2.14 on 2022-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete'), ('In-Progress', 'In-Progress')], default='Incomplete', max_length=200),
        ),
    ]
