# Generated by Django 3.2.14 on 2022-07-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Important', 'Important'), ('Basic', 'Basic'), ('Urgent', 'Urgent')], default='Basic', max_length=200),
        ),
    ]
